kind: Service
apiVersion: v1
metadata:
  name: jual-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: jual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jual-deploy
  namespace: production
spec:
  selector:
    matchLabels:
      app: jual
  replicas: 2
  template:
    metadata:
      labels:
        app: jual
    spec:
      containers:
<<<<<<< HEAD
      - name: php-jual
        image: farman17/penjualan-ci
        ports:
          - containerPort: 80
   
=======
      - name: php-pesbuk
        image: farman17/penjualan-ci
        ports:
          - containerPort: 80
       
>>>>>>> ad2f0e39cd0faff3a234c52fe91a7ed745d56195

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jual-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: landing.dailybugis.my.id
    http:
      paths:
      #- path: /
      - backend:
          serviceName: jual-service
          servicePort: 80

